ConsumeWebAPI/ConsumeWebAPI/Models/BranchViewModel.cs
namespace ConsumeWebAPI.Models
{
    public class BranchViewModel
    {
        public int Id { get; set; }
        public string location { get; set; }
    }
}

ConsumeWebAPI/ConsumeWebAPI/Controllers/BranchController.cs
using ConsumeWebAPI.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Data;
using System.Text;

namespace ConsumeWebAPI.Controllers
{
    public class BranchController : Controller
    {
        Uri BaseURL = new Uri("http://localhost:57163/api/");
        HttpClient client;
        public BranchController()
        {
            client = new HttpClient();
            client.BaseAddress = BaseURL;
        }
        public ActionResult Index()
        {
            List<BranchViewModel> branchList = new List<BranchViewModel>();
            HttpResponseMessage response = client.GetAsync($"{client.BaseAddress}Branch/getAll").Result;
            if (response.IsSuccessStatusCode)
            {
                string data =  response.Content.ReadAsStringAsync().Result;
                branchList = JsonConvert.DeserializeObject<List<BranchViewModel>>(data);
            }
            return View(branchList);
        }
        public ActionResult create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(BranchViewModel branch)
        {
            string data = JsonConvert.SerializeObject(branch);
            StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.PostAsync($"{client.BaseAddress}Branch/Add",content).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult Details(int id)
        {
            BranchViewModel branch = new BranchViewModel();
            HttpResponseMessage response = client.GetAsync($"{client.BaseAddress}Branch/getById/{id}").Result;
            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                branch = JsonConvert.DeserializeObject<BranchViewModel>(data);
            }
            return View(branch);
        }

    }
}

ConsumeWebAPI/ConsumeWebAPI/Views/Branch/Create.cshtml
@*@model ConsumeWebAPI.Models.BranchViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>BranchViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Branch" asp-route-id="@Model.Id">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="location" class="control-label"></label>
                <input asp-for="location" class="form-control" />
                <span asp-validation-for="location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>*@

@*<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}*@

@model BranchViewModel
@{
    //Layout = null;
    ViewBag.Title = "Create Brach";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Show</title>
    <link rel="stylesheet" href = "/lib/bootstrap/dist/css/bootstrap.css"/>
</head>
<body>
    <div class="container">
        <form asp-action="Create" asp-controller="Branch">
            @*<label asp-for="Id"  class="control-label"></label>*@
             <input asp-for=Id type="hidden" class="form-control mt-5" placeholder="BranchId" />
             <label asp-for="location" class="control-label"></label>
             <input asp-for=location  class="form-control mt-5" placeholder="BranchLocation" />
            
             <input type="submit" value="Add" class="btn btn-success mt-5"/>
        </form>
         <a asp-action="Index" asp-controller="branch" class="btn btn-success mt-5">back to List</a>
    </div>
</body>
</html>

ConsumeWebAPI/ConsumeWebAPI/Views/Branch/Details.cshtml
@model ConsumeWebAPI.Models.BranchViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div class="container">
    <div class="row mt-5 g-0">
        
        <div class = "col-8">
            <h4>Id:@Model.Id</h4>
            <h4>Location:@Model.location</h4>
        </div>
    </div>
    <a asp-action="Index" asp-controller="branch" class="btn btn-success mt-5">back to List</a>

ConsumeWebAPI/ConsumeWebAPI/Views/Branch/Index.cshtml
@model IEnumerable<ConsumeWebAPI.Models.BranchViewModel>

@{
    ViewData["Title"] = "All Branches";
}

<div class="container">
<h1>ALL BRANCHES</h1>

<p>
     <a asp-action ="create" asp-controller = "branch"  class="btn btn-success mt-5">Create Branch</a>
</p>
@*<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.location)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.location)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id  })
            </td>
        </tr>
}
    </tbody>
</table>*@
<table class="table table-bordered table-hover" width="50%">
    <thead>
    <tr>
        <th>
              BranchId
        </th>
        <th>
             BranchLocation
        </th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.location</td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary">Details</a>
            </td>
        </tr>
    }
    </tbody>
</table>
</div>